version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          node --version
          java --version
          google-chrome --version
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - restore_cache:
          key: dependency-cache-client-{{ checksum "client/package-lock.json" }}
      - run:
          name: install-client-packages
          command: pushd client && npm install && popd 
      - save_cache:
          key: dependency-cache-client-{{ checksum "client/package-lock.json" }}
          paths:
            - ./client/node_modules
      - restore_cache:
          key: dependency-cache-server-{{ checksum "server/package-lock.json" }}
      - run:
          name: install-server-packages
          command: pushd server && npm install && popd
      - save_cache:
          key: dependency-cache-server-{{ checksum "server/package-lock.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: lint
          command: /bin/bash npm run lint 
      - run:
          name: test
          command: /bin/bash npm run test 